import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#edf1f6",
        "surface-container": "#eaeef3",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001e2c",
        "on-error-container": "#93000a",
        "on-surface-variant": "#3e484f",
        "surface-variant": "#dfe3e8",
        "on-secondary-fixed-variant": "#910031",
        "on-secondary-container": "#fffbff",
        "surface-bright": "#f6fafe",
        "on-error": "#ffffff",
        "surface-ice": "#f8f9fa",
        tertiary: "#885200",
        "on-secondary": "#ffffff",
        "institutional-navy": "#001b3f",
        "on-tertiary": "#ffffff",
        "on-surface": "#171c20",
        "on-primary-container": "#003b53",
        "on-secondary-fixed": "#400011",
        "surface-container-high": "#e4e9ed",
        "secondary-fixed": "#ffd9dc",
        background: "#f6fafe",
        "tertiary-fixed": "#ffdcbb",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#de8e26",
        "on-primary-fixed-variant": "#004c69",
        primary: "#00668a",
        "on-background": "#171c20",
        "surface-dim": "#d6dadf",
        "surface-container-low": "#f0f4f9",
        "on-tertiary-fixed-variant": "#683d00",
        error: "#ba1a1a",
        "on-tertiary-container": "#512f00",
        "error-container": "#ffdad6",
        "inverse-surface": "#2c3135",
        "primary-container": "#29abe2",
        "secondary-container": "#e31855",
        outline: "#6e7880",
        "surface-container-highest": "#dfe3e8",
        surface: "#f6fafe",
        "primary-fixed": "#c4e7ff",
        secondary: "#b90041",
        "on-tertiary-fixed": "#2c1700",
        "secondary-fixed-dim": "#ffb2ba",
        "primary-fixed-dim": "#7bd0ff",
        "inverse-primary": "#7bd0ff",
        "munganga-crimson": "#cd163f",
        "outline-variant": "#bdc8d0",
        "surface-tint": "#00668a",
        "tertiary-fixed-dim": "#ffb86a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1280px",
        "section-lg": "80px",
        "section-padding": "80px",
        unit: "8px",
        "gutter-desktop": "24px",
        gutter: "24px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "stack-lg": "32px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
